# Control4 AMP Service
c4_services:
  input_select:
    zone1_c4_input:
      name: Audio Input
      options:
        - Tuner
        - Volumio
        - Bluetooth
    zone1_amp_input:
      name: Zone Input
      options:
        - 1
        - 3
        - 4
    zone2_c4_input:
      name: Audio Input
      options:
        - Tuner
        - Volumio
        - Bluetooth
    zone2_input:
      name: Zone Input
      options:
        - 2
        - 3
        - 4
    zone3_c4_input:
      name: Audio Input
      options:
        - Tuner
        - Volumio
        - Bluetooth
    zone3_amp_input:
      name: Zone Input
      options:
        - 2
        - 3
        - 4      
    zone4_c4_input:
      name: Audio Input
      options:
        - Tuner
        - Volumio
        - Bluetooth
    zone4_amp_input:
      name: Zone Input
      options:
        - 2
        - 3
        - 4
  input_number:
    zone1_amp_volume:
      name: Volume
      min: 0
      max: 1
      step: .01
      initial: .04
    zone2_amp_volume:
      name: Volume
      min: 0
      max: 1
      step: .01
      initial: .04
    zone3_amp_volume:
      name: Volume
      min: 0
      max: 1
      step: .01
      initial: .04
    zone4_amp_volume:
      name: Volume
      min: 0
      max: 1
      step: .01
      initial: .04  
  input_boolean:
    switch_state_1:
      name: Zone 1 Switch
    switch_state_2:
      name: Zone 2 Switch
    switch_state_3:
      name: Zone 3 Switch
    switch_state_4:
      name: Zone 4 Switch
  switch:
    - platform: template
      switches:
        zone1_switch:
          friendly_name: Zone 1
          value_template: "{{ is_state('input_boolean.switch_state_1', 'on') }}"
          turn_on:
            - service: c4_services.handle_zone1_amp_on_select
            - service: input_boolean.turn_on
              data:
                entity_id: input_boolean.switch_state_1
          turn_off:
            - service: c4_services.handle_zone1_amp_off_select
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.switch_state_1
    - platform: template
      switches:
        zone2_switch:
          friendly_name: Zone 2
          value_template: "{{ is_state('input_boolean.switch_state_2', 'on') }}"
          turn_on:
            - service: c4_services.handle_zone2_amp_on_select
            - service: input_boolean.turn_on
              data:
                entity_id: input_boolean.switch_state_2
          turn_off:
            - service: c4_services.handle_zone2_amp_off_select
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.switch_state_2
    - platform: template
      switches:
        zone3_switch:
          friendly_name: Zone 3
          value_template: "{{ is_state('input_boolean.switch_state_3', 'on') }}"
          turn_on:
            - service: c4_services.handle_zone3_amp_on_select
            - service: input_boolean.turn_on
              data:
                entity_id: input_boolean.switch_state_3
          turn_off:
            - service: c4_services.handle_zone3_amp_off_select
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.switch_state_3              
    - platform: template
      switches:
        zone4_switch:
          friendly_name: Zone 4
          value_template: "{{ is_state('input_boolean.switch_state_3', 'on') }}"
          turn_on:
            - service: c4_services.handle_zone3_amp_on_select
            - service: input_boolean.turn_on
              data:
                entity_id: input_boolean.switch_state_3
          turn_off:
            - service: c4_services.handle_zone3_amp_off_select
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.switch_state_3
